version: '3'
services:
  web:
    build: .
    command: foreman start -f Procfile.dev -p 3000
    volumes:
      - .:/featuretoggles
    ports:
      - "3000:3000"
    links:
      - database
    tty: true
    stdin_open: true
  database:
    image: mongo:latest
    container_name: feature_toggle_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null
    ports:
        - "27017:27017"
